from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Autocompletar formularios
    Generated by: JONATAN ALEXANDER MORA LADINO (jamora649@ucatolica.edu.co)
    Generated on 10/13/2021, 15:54:52
"""


@pytest.fixture()
def driver():
    driver = webdriver.Firefox(token="AJINYVeRnsa_fctNQarCvNuzlv3Ck0fNyGkTXrfx0-g",
                               project_name="My first Project",
                               job_name="Autocompletar formularios")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """El sistema deberá mostrar dos cajones para ingresar colores en inglés, tan pronto se ingresa la letra inicial debe mostrar opciones relacionadas con lo ingresado.."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://demoqa.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'svg2'
    svg2 = driver.find_element(By.XPATH,
                               "//div[4]//*[name()='svg']")
    svg2.click()

    # 3. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 4. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 5. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 6. Click 'Auto Complete'
    auto_complete = driver.find_element(By.XPATH,
                                        "//span[. = 'Auto Complete']")
    auto_complete.click()

    # 7. Scroll window by ('0','-300')
    driver.execute_script("window.scrollBy(0,-300)")

    # 8. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[2]/div[2]/div[1]/div[1]/div/div/div/div/div[1]")
    div.click()

    # 9. Type 'B' in 'autoCompleteMultipleInput'
    autocompletemultipleinput = driver.find_element(By.CSS_SELECTOR,
                                                    "#autoCompleteMultipleInput")
    autocompletemultipleinput.send_keys("B")

    # 10. Click 'Blue'
    blue = driver.find_element(By.CSS_SELECTOR,
                               "#react-select-2-option-0")
    blue.click()

    # 11. Click 'DIV1'
    div1 = driver.find_element(By.XPATH,
                               "//div[2]/div[1]/div[2]/div/div/div/div/div[1]")
    div1.click()

    # 12. Type 'Bla' in 'autoCompleteSingleInput'
    autocompletesingleinput = driver.find_element(By.CSS_SELECTOR,
                                                  "#autoCompleteSingleInput")
    autocompletesingleinput.send_keys("Bla")

    # 13. Click 'Black'
    black = driver.find_element(By.CSS_SELECTOR,
                                "#react-select-3-option-0")
    black.click()
