from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Usar Text Box
    Generated by: JONATAN ALEXANDER MORA LADINO (jamora649@ucatolica.edu.co)
    Generated on 10/13/2021, 15:46:04
"""


@pytest.fixture()
def driver():
    driver = webdriver.Edge(token="AJINYVeRnsa_fctNQarCvNuzlv3Ck0fNyGkTXrfx0-g",
                            project_name="My first Project",
                            job_name="Usar Text Box")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """El sistema deberá mostrar el formulario de registro de un usuario, permitir su diligenciamiento y registro."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://demoqa.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'svg'
    svg = driver.find_element(By.XPATH,
                              "//div[1]/div/div/*[name()='svg']")
    svg.click()

    # 3. Click 'Text Box'
    text_box = driver.find_element(By.XPATH,
                                   "//span[. = 'Text Box']")
    text_box.click()

    # 4. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 5. Click 'Full Name'
    full_name = driver.find_element(By.CSS_SELECTOR,
                                    "#userName")
    full_name.click()

    # 6. Type 'Jonatan Alexander Mora' in 'Full Name'
    full_name = driver.find_element(By.CSS_SELECTOR,
                                    "#userName")
    full_name.send_keys("Jonatan Alexander Mora")

    # 7. Click 'name@example.com'
    name_example_com = driver.find_element(By.CSS_SELECTOR,
                                           "#userEmail")
    name_example_com.click()

    # 8. Type 'jamora649@ucatolica.edu.co' in 'name@example.com'
    name_example_com = driver.find_element(By.CSS_SELECTOR,
                                           "#userEmail")
    name_example_com.send_keys("jamora649@ucatolica.edu.co")

    # 9. Click 'Current Address'
    current_address = driver.find_element(By.CSS_SELECTOR,
                                          "#currentAddress")
    current_address.click()

    # 10. Type 'Calle 21b' in 'Current Address'
    current_address = driver.find_element(By.CSS_SELECTOR,
                                          "#currentAddress")
    current_address.send_keys("Calle 21b")

    # 11. Click 'permanentAddress'
    permanentaddress = driver.find_element(By.CSS_SELECTOR,
                                           "#permanentAddress")
    permanentaddress.click()

    # 12. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 13. Type 'Calle 21b' in 'permanentAddress'
    permanentaddress = driver.find_element(By.CSS_SELECTOR,
                                           "#permanentAddress")
    permanentaddress.send_keys("Calle 21b")

    # 14. Click 'Submit'
    submit = driver.find_element(By.CSS_SELECTOR,
                                 "#submit")
    submit.click()
