from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Cargar/Descargar archivos
    Generated by: JONATAN ALEXANDER MORA LADINO (jamora649@ucatolica.edu.co)
    Generated on 10/13/2021, 15:45:42
"""


@pytest.fixture()
def driver():
    driver = webdriver.Edge(token="AJINYVeRnsa_fctNQarCvNuzlv3Ck0fNyGkTXrfx0-g",
                            project_name="My first Project",
                            job_name="Cargar/Descargar archivos")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """El sistema deberá mostrar dos cajones para ingresar colores en inglés, tan pronto se ingresa la letra inicial debe mostrar opciones relacionadas con lo ingresado."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://demoqa.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'svg'
    svg = driver.find_element(By.XPATH,
                              "//div[1]/div/div/*[name()='svg']")
    svg.click()

    # 3. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 4. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 5. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 6. Click 'Upload and Download'
    upload_and_download = driver.find_element(By.XPATH,
                                              "//span[. = 'Upload and Download']")
    upload_and_download.click()

    # 7. Scroll window by ('0','-300')
    driver.execute_script("window.scrollBy(0,-300)")

    # 8. Click 'uploadFile'
    uploadfile = driver.find_element(By.CSS_SELECTOR,
                                     "#uploadFile")
    uploadfile.click()

    # 9. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 10. Type 'C:\fakepath\12.png' in 'uploadFile'
    uploadfile = driver.find_element(By.CSS_SELECTOR,
                                     "#uploadFile")
    uploadfile.send_keys("C:\\fakepath\\12.png")

    # 11. Scroll window by ('0','-300')
    driver.execute_script("window.scrollBy(0,-300)")

    # 12. Click 'Download'
    download = driver.find_element(By.CSS_SELECTOR,
                                   "#downloadButton")
    download.click()
