from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: pruebas SW
    Package: TestProject.Generated.Tests.PruebasSw
    Test: Mostrar notificaciones
    Generated by: Dina Hurtado (nighwish22@gmail.com)
    Generated on 10/28/2021, 03:11:11
"""


@pytest.fixture()
def driver():
    driver = webdriver.Firefox(token="15wM28xhucAOs7etwSr8IjyrLJhbrKI9iiG7X_EJ6DQ",
                               project_name="pruebas SW",
                               job_name="Mostrar notificaciones")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Generar un mensaje de alerta en el navegador después de 5 segundos."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://demoqa.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Ad.Plus Advertising1'
    ad_plus_advertising1 = driver.find_element(By.XPATH,
                                               "//body/div[1]//img")
    ad_plus_advertising1.click()

    # 3. Scroll window by ('0','367')
    driver.execute_script("window.scrollBy(0,367)")

    # 4. Click 'DIV10'
    div10 = driver.find_element(By.XPATH,
                                "//div[2]/div/div/div[2]/div/div[3]")
    div10.click()

    # 5. Scroll window by ('0','-367')
    driver.execute_script("window.scrollBy(0,-367)")

    # 6. Scroll window by ('0','331')
    driver.execute_script("window.scrollBy(0,331)")

    # 7. Click 'item-1'
    item_1 = driver.find_element(By.XPATH,
                                 "//div[3]//li[2]")
    item_1.click()

    # 8. Scroll window by ('0','-331')
    driver.execute_script("window.scrollBy(0,-331)")

    # 9. Click 'Click me'
    click_me = driver.find_element(By.CSS_SELECTOR,
                                   "#timerAlertButton")
    click_me.click()
