from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: pruebas SW
    Package: TestProject.Generated.Tests.PruebasSw
    Test: Ingresar al Login
    Generated by: Dina Hurtado (nighwish22@gmail.com)
    Generated on 10/28/2021, 03:06:04
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="15wM28xhucAOs7etwSr8IjyrLJhbrKI9iiG7X_EJ6DQ",
                              project_name="pruebas SW",
                              job_name="Ingresar al Login")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """iniciar sesión en la tienda de libros."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://demoqa.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Ad.Plus Advertising1'
    ad_plus_advertising1 = driver.find_element(By.XPATH,
                                               "//body/div[1]//img")
    ad_plus_advertising1.click()

    # 3. Scroll window by ('0','680')
    driver.execute_script("window.scrollBy(0,680)")

    # 4. Click 'DIV11'
    div11 = driver.find_element(By.XPATH,
                                "//div[6]")
    div11.click()

    # 5. Scroll window by ('0','-680')
    driver.execute_script("window.scrollBy(0,-680)")

    # 6. Scroll window by ('0','663')
    driver.execute_script("window.scrollBy(0,663)")

    # 7. Click 'item-01'
    item_01 = driver.find_element(By.XPATH,
                                  "//div[6]//li[1]")
    item_01.click()

    # 8. Scroll window by ('0','-663')
    driver.execute_script("window.scrollBy(0,-663)")

    # 9. Click 'UserName'
    username = driver.find_element(By.CSS_SELECTOR,
                                   "#userName")
    username.click()

    # 10. Type 'Pruebas' in 'UserName'
    username = driver.find_element(By.CSS_SELECTOR,
                                   "#userName")
    username.send_keys("Pruebas")

    # 11. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 12. Type 'Dimi2209*' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys("Dimi2209*")

    # 13. Click 'Login'
    login = driver.find_element(By.CSS_SELECTOR,
                                "#login")
    login.click()

    # 14. Scroll window by ('0','347')
    driver.execute_script("window.scrollBy(0,347)")

    # 15. Scroll window by ('0','-173')
    driver.execute_script("window.scrollBy(0,-173)")

    # 16. Scroll window by ('0','45')
    driver.execute_script("window.scrollBy(0,45)")

    # 17. Scroll window by ('0','-163')
    driver.execute_script("window.scrollBy(0,-163)")

    # 18. Click 'Log out'
    log_out = driver.find_element(By.XPATH,
                                  "//button[. = 'Log out']")
    log_out.click()

    # 19. Scroll window by ('0','-56')
    driver.execute_script("window.scrollBy(0,-56)")
