from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Agregar registros en Web Tables
    Generated by: JONATAN ALEXANDER MORA LADINO (jamora649@ucatolica.edu.co)
    Generated on 10/13/2021, 15:55:11
"""


@pytest.fixture()
def driver():
    driver = webdriver.Firefox(token="AJINYVeRnsa_fctNQarCvNuzlv3Ck0fNyGkTXrfx0-g",
                               project_name="My first Project",
                               job_name="Agregar registros en Web Tables")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """El sistema deberá mostrar el formulario y opciones de edición."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://demoqa.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'svg'
    svg = driver.find_element(By.XPATH,
                              "//div[1]/div/div/*[name()='svg']")
    svg.click()

    # 3. Click 'Web Tables'
    web_tables = driver.find_element(By.XPATH,
                                     "//span[. = 'Web Tables']")
    web_tables.click()

    # 4. Click 'Add'
    add = driver.find_element(By.CSS_SELECTOR,
                              "#addNewRecordButton")
    add.click()

    # 5. Click 'First Name'
    first_name = driver.find_element(By.CSS_SELECTOR,
                                     "#firstName")
    first_name.click()

    # 6. Type 'Jonatan' in 'First Name'
    first_name = driver.find_element(By.CSS_SELECTOR,
                                     "#firstName")
    first_name.send_keys("Jonatan")

    # 7. Click 'Last Name'
    last_name = driver.find_element(By.CSS_SELECTOR,
                                    "#lastName")
    last_name.click()

    # 8. Type 'Mora' in 'Last Name'
    last_name = driver.find_element(By.CSS_SELECTOR,
                                    "#lastName")
    last_name.send_keys("Mora")

    # 9. Click 'name@example.com'
    name_example_com = driver.find_element(By.CSS_SELECTOR,
                                           "#userEmail")
    name_example_com.click()

    # 10. Type 'jamora649@ucatolica.edu.co' in 'name@example.com'
    name_example_com = driver.find_element(By.CSS_SELECTOR,
                                           "#userEmail")
    name_example_com.send_keys("jamora649@ucatolica.edu.co")

    # 11. Click 'Age'
    age = driver.find_element(By.CSS_SELECTOR,
                              "#age")
    age.click()

    # 12. Type '33' in 'Age'
    age = driver.find_element(By.CSS_SELECTOR,
                              "#age")
    age.send_keys("33")

    # 13. Click 'Salary'
    salary = driver.find_element(By.CSS_SELECTOR,
                                 "#salary")
    salary.click()

    # 14. Type '200000' in 'Salary'
    salary = driver.find_element(By.CSS_SELECTOR,
                                 "#salary")
    salary.send_keys("200000")

    # 15. Click 'Department'
    department = driver.find_element(By.CSS_SELECTOR,
                                     "#department")
    department.click()

    # 16. Type 'Bogotá' in 'Department'
    department = driver.find_element(By.CSS_SELECTOR,
                                     "#department")
    department.send_keys("Bogotá")

    # 17. Click 'Submit'
    submit = driver.find_element(By.CSS_SELECTOR,
                                 "#submit")
    submit.click()

    # 18. Click 'Jonatan'
    jonatan = driver.find_element(By.XPATH,
                                  "//div[. = 'Jonatan']")
    jonatan.click()

    # 19. Click 'svg1'
    svg1 = driver.find_element(By.XPATH,
                               "//div[4]/div/div[7]/div/span[1]/*")
    svg1.click()
